from __future__ import annotations

from math import sqrt

from app.core.schemas import Action, ParkingScene, ReplayResult, SimStep
from app.sim.bicycle import step_bicycle
from app.sim.lidar import scan_lidar
from app.sim.scene import goal_metrics, has_collision, is_out_of_bounds, is_success


def has_scripted_replay(preset_key: str) -> bool:
    return preset_key in {"easy-parallel", "easy-tight-squeeze"}


def scripted_replay(
    preset_key: str,
    scene: ParkingScene,
    *,
    include_lidar: bool = False,
) -> ReplayResult:
    if not has_scripted_replay(preset_key):
        raise KeyError(f"No scripted replay for preset: {preset_key}")

    steps: list[SimStep] = []
    reason = "actions_exhausted"
    success = False
    terminated = False
    state = scene.start

    for index, action in enumerate(_parallel_slot_actions(scene)[: scene.max_steps], start=1):
        state = step_bicycle(state, action, scene.car_spec, scene.dt)
        collision = has_collision(scene, state)
        out_of_bounds = is_out_of_bounds(scene, state)
        step_success = is_success(scene, state)
        steps.append(
            SimStep(
                index=index,
                state=state,
                action=action,
                metrics=goal_metrics(scene, state),
                collision=collision,
                out_of_bounds=out_of_bounds,
                success=step_success,
                lidar_distances=scan_lidar(scene, state) if include_lidar else None,
            )
        )

        if collision:
            reason = "collision"
            terminated = True
            break
        if out_of_bounds:
            reason = "out_of_bounds"
            terminated = True
            break

    if not terminated:
        success = steps[-1].success if steps else False
        if success:
            reason = "success"
            terminated = True
        elif len(steps) >= scene.max_steps:
            reason = "timeout"

    return ReplayResult(
        scene_id=scene.id,
        steps=steps,
        final_state=steps[-1].state if steps else scene.start,
        reason=reason,
        success=success,
        terminated=terminated,
    )


def _clip(value: float, lower: float, upper: float) -> float:
    return min(max(value, lower), upper)


def _parallel_slot_actions(scene: ParkingScene) -> list[Action]:
    actions: list[Action] = []
    state = scene.start

    # Stage the car ahead of the open bay, then execute a reverse parallel
    # maneuver. These are real controls, not pose samples; replay states are
    # generated by the same bicycle stepper used for learned policies.
    staging_x = 8.2
    for _ in range(scene.max_steps):
        remaining = staging_x - state.x
        if remaining <= 0.25 and abs(state.v) <= 0.05:
            break

        target_speed = min(2.4, sqrt(max(0.0, 2.0 * max(0.0, remaining - 0.2))))
        acceleration = _clip(
            (target_speed - state.v) / (scene.car_spec.max_accel * scene.dt),
            -0.8,
            0.5,
        )
        action = Action(acceleration=acceleration, steering_rate=0.0)
        actions.append(action)
        state = step_bicycle(state, action, scene.car_spec, scene.dt)

    reverse_phases = (
        (24, -0.32, 1.0),
        (15, 0.12, -1.0),
        (20, 0.32, -1.0),
        (5, 0.0, 1.0),
    )
    for duration, acceleration, steering_rate in reverse_phases:
        for _ in range(duration):
            action = Action(acceleration=acceleration, steering_rate=steering_rate)
            actions.append(action)
            state = step_bicycle(state, action, scene.car_spec, scene.dt)

    return actions
